# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Programa_medico_Grafico.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(917, 504)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.nivel_1 = QtWidgets.QTabWidget(self.centralwidget)
        self.nivel_1.setGeometry(QtCore.QRect(0, 50, 911, 411))
        self.nivel_1.setObjectName("nivel_1")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.lineEdit = QtWidgets.QLineEdit(self.tab)
        self.lineEdit.setGeometry(QtCore.QRect(0, 0, 231, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.nivel_2 = QtWidgets.QTabWidget(self.tab)
        self.nivel_2.setGeometry(QtCore.QRect(0, 0, 921, 391))
        self.nivel_2.setObjectName("nivel_2")
        self.tab_17 = QtWidgets.QWidget()
        self.tab_17.setObjectName("tab_17")
        self.num_expediente_1 = QtWidgets.QLineEdit(self.tab_17)
        self.num_expediente_1.setGeometry(QtCore.QRect(200, 10, 421, 20))
        self.num_expediente_1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.num_expediente_1.setObjectName("num_expediente_1")
        self.num_expediente_0 = QtWidgets.QLineEdit(self.tab_17)
        self.num_expediente_0.setGeometry(QtCore.QRect(10, 10, 181, 20))
        self.num_expediente_0.setReadOnly(True)
        self.num_expediente_0.setObjectName("num_expediente_0")
        self.titulo_0 = QtWidgets.QLineEdit(self.tab_17)
        self.titulo_0.setGeometry(QtCore.QRect(10, 30, 181, 20))
        self.titulo_0.setReadOnly(True)
        self.titulo_0.setObjectName("titulo_0")
        self.nombres = QtWidgets.QLineEdit(self.tab_17)
        self.nombres.setGeometry(QtCore.QRect(10, 50, 181, 20))
        self.nombres.setReadOnly(True)
        self.nombres.setObjectName("nombres")
        self.apellidos = QtWidgets.QLineEdit(self.tab_17)
        self.apellidos.setGeometry(QtCore.QRect(10, 70, 181, 20))
        self.apellidos.setReadOnly(True)
        self.apellidos.setObjectName("apellidos")
        self.domicilio_0 = QtWidgets.QLineEdit(self.tab_17)
        self.domicilio_0.setGeometry(QtCore.QRect(10, 90, 181, 20))
        self.domicilio_0.setReadOnly(True)
        self.domicilio_0.setObjectName("domicilio_0")
        self.ciudad_0 = QtWidgets.QLineEdit(self.tab_17)
        self.ciudad_0.setGeometry(QtCore.QRect(10, 110, 181, 20))
        self.ciudad_0.setReadOnly(True)
        self.ciudad_0.setObjectName("ciudad_0")
        self.estado_0 = QtWidgets.QLineEdit(self.tab_17)
        self.estado_0.setGeometry(QtCore.QRect(10, 130, 181, 20))
        self.estado_0.setReadOnly(True)
        self.estado_0.setObjectName("estado_0")
        self.cod_postal_0 = QtWidgets.QLineEdit(self.tab_17)
        self.cod_postal_0.setGeometry(QtCore.QRect(10, 150, 181, 20))
        self.cod_postal_0.setReadOnly(True)
        self.cod_postal_0.setObjectName("cod_postal_0")
        self.medico_0 = QtWidgets.QLineEdit(self.tab_17)
        self.medico_0.setGeometry(QtCore.QRect(10, 170, 181, 20))
        self.medico_0.setReadOnly(True)
        self.medico_0.setObjectName("medico_0")
        self.sexo_0 = QtWidgets.QLineEdit(self.tab_17)
        self.sexo_0.setGeometry(QtCore.QRect(10, 190, 181, 20))
        self.sexo_0.setReadOnly(True)
        self.sexo_0.setObjectName("sexo_0")
        self.fech_nac_0 = QtWidgets.QLineEdit(self.tab_17)
        self.fech_nac_0.setGeometry(QtCore.QRect(10, 210, 181, 20))
        self.fech_nac_0.setReadOnly(True)
        self.fech_nac_0.setObjectName("fech_nac_0")
        self.lug_nac_0 = QtWidgets.QLineEdit(self.tab_17)
        self.lug_nac_0.setGeometry(QtCore.QRect(10, 230, 181, 20))
        self.lug_nac_0.setReadOnly(True)
        self.lug_nac_0.setObjectName("lug_nac_0")
        self.correo_0 = QtWidgets.QLineEdit(self.tab_17)
        self.correo_0.setGeometry(QtCore.QRect(10, 250, 181, 20))
        self.correo_0.setReadOnly(True)
        self.correo_0.setObjectName("correo_0")
        self.titulo_1 = QtWidgets.QLineEdit(self.tab_17)
        self.titulo_1.setGeometry(QtCore.QRect(200, 30, 421, 20))
        self.titulo_1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.titulo_1.setObjectName("titulo_1")
        self.nombres_1 = QtWidgets.QLineEdit(self.tab_17)
        self.nombres_1.setGeometry(QtCore.QRect(200, 50, 201, 20))
        self.nombres_1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.nombres_1.setObjectName("nombres_1")
        self.apellidos_1 = QtWidgets.QLineEdit(self.tab_17)
        self.apellidos_1.setGeometry(QtCore.QRect(200, 70, 201, 20))
        self.apellidos_1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.apellidos_1.setObjectName("apellidos_1")
        self.domicilio_1 = QtWidgets.QLineEdit(self.tab_17)
        self.domicilio_1.setGeometry(QtCore.QRect(200, 90, 421, 20))
        self.domicilio_1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.domicilio_1.setObjectName("domicilio_1")
        self.cod_postal_1 = QtWidgets.QLineEdit(self.tab_17)
        self.cod_postal_1.setGeometry(QtCore.QRect(200, 150, 421, 20))
        self.cod_postal_1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.cod_postal_1.setObjectName("cod_postal_1")
        self.lug_nac_1 = QtWidgets.QLineEdit(self.tab_17)
        self.lug_nac_1.setGeometry(QtCore.QRect(200, 230, 201, 20))
        self.lug_nac_1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lug_nac_1.setObjectName("lug_nac_1")
        self.correo_1 = QtWidgets.QLineEdit(self.tab_17)
        self.correo_1.setGeometry(QtCore.QRect(200, 250, 201, 20))
        self.correo_1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.correo_1.setObjectName("correo_1")
        self.observaciones_0 = QtWidgets.QLineEdit(self.tab_17)
        self.observaciones_0.setGeometry(QtCore.QRect(10, 270, 181, 20))
        self.observaciones_0.setReadOnly(True)
        self.observaciones_0.setObjectName("observaciones_0")
        self.observaciones_1 = QtWidgets.QLineEdit(self.tab_17)
        self.observaciones_1.setGeometry(QtCore.QRect(200, 270, 421, 81))
        self.observaciones_1.setObjectName("observaciones_1")
        self.nombres_2 = QtWidgets.QLineEdit(self.tab_17)
        self.nombres_2.setGeometry(QtCore.QRect(410, 50, 211, 20))
        self.nombres_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.nombres_2.setObjectName("nombres_2")
        self.apellidos_2 = QtWidgets.QLineEdit(self.tab_17)
        self.apellidos_2.setGeometry(QtCore.QRect(410, 70, 211, 20))
        self.apellidos_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.apellidos_2.setObjectName("apellidos_2")
        self.ciudad_1_box = QtWidgets.QComboBox(self.tab_17)
        self.ciudad_1_box.setGeometry(QtCore.QRect(200, 110, 421, 22))
        self.ciudad_1_box.setObjectName("ciudad_1_box")
        self.ciudad_1_box.addItem("")
        self.ciudad_1_box.setItemText(0, "")
        self.ciudad_1_box.addItem("")
        self.ciudad_1_box.addItem("")
        self.ciudad_1_box.addItem("")
        self.ciudad_1_box.addItem("")
        self.ciudad_1_box.addItem("")
        self.ciudad_1_box.addItem("")
        self.ciudad_1_box.addItem("")
        self.ciudad_1_box.addItem("")
        self.ciudad_1_box.addItem("")
        self.ciudad_1_box.addItem("")
        self.ciudad_1_box.addItem("")
        self.ciudad_1_box.addItem("")
        self.estado_1_box = QtWidgets.QComboBox(self.tab_17)
        self.estado_1_box.setGeometry(QtCore.QRect(200, 130, 421, 22))
        self.estado_1_box.setObjectName("estado_1_box")
        self.estado_1_box.addItem("")
        self.estado_1_box.setItemText(0, "")
        self.estado_1_box.addItem("")
        self.estado_1_box.addItem("")
        self.sexo_1_box = QtWidgets.QComboBox(self.tab_17)
        self.sexo_1_box.setGeometry(QtCore.QRect(200, 190, 201, 22))
        self.sexo_1_box.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sexo_1_box.setMaxCount(2147483647)
        self.sexo_1_box.setObjectName("sexo_1_box")
        self.sexo_1_box.addItem("")
        self.sexo_1_box.setItemText(0, "")
        self.sexo_1_box.addItem("")
        self.sexo_1_box.addItem("")
        self.medico_1_box = QtWidgets.QComboBox(self.tab_17)
        self.medico_1_box.setGeometry(QtCore.QRect(200, 170, 691, 22))
        self.medico_1_box.setObjectName("medico_1_box")
        self.medico_1_box.addItem("")
        self.medico_1_box.setItemText(0, "")
        self.medico_1_box.addItem("")
        self.medico_1_box.addItem("")
        self.num_seguro_0 = QtWidgets.QLineEdit(self.tab_17)
        self.num_seguro_0.setGeometry(QtCore.QRect(420, 190, 201, 20))
        self.num_seguro_0.setReadOnly(True)
        self.num_seguro_0.setObjectName("num_seguro_0")
        self.edad_0 = QtWidgets.QLineEdit(self.tab_17)
        self.edad_0.setGeometry(QtCore.QRect(420, 210, 201, 20))
        self.edad_0.setReadOnly(True)
        self.edad_0.setObjectName("edad_0")
        self.telf_dom_0 = QtWidgets.QLineEdit(self.tab_17)
        self.telf_dom_0.setGeometry(QtCore.QRect(420, 230, 201, 20))
        self.telf_dom_0.setReadOnly(True)
        self.telf_dom_0.setObjectName("telf_dom_0")
        self.telf_ofi_0 = QtWidgets.QLineEdit(self.tab_17)
        self.telf_ofi_0.setGeometry(QtCore.QRect(420, 250, 201, 20))
        self.telf_ofi_0.setReadOnly(True)
        self.telf_ofi_0.setObjectName("telf_ofi_0")
        self.num_seguro_1 = QtWidgets.QLineEdit(self.tab_17)
        self.num_seguro_1.setGeometry(QtCore.QRect(630, 190, 261, 20))
        self.num_seguro_1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.num_seguro_1.setObjectName("num_seguro_1")
        self.edad_1 = QtWidgets.QLineEdit(self.tab_17)
        self.edad_1.setGeometry(QtCore.QRect(630, 210, 261, 20))
        self.edad_1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.edad_1.setObjectName("edad_1")
        self.telf_dom_1 = QtWidgets.QLineEdit(self.tab_17)
        self.telf_dom_1.setGeometry(QtCore.QRect(630, 230, 261, 20))
        self.telf_dom_1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.telf_dom_1.setObjectName("telf_dom_1")
        self.telf_ofi_1 = QtWidgets.QLineEdit(self.tab_17)
        self.telf_ofi_1.setGeometry(QtCore.QRect(630, 250, 261, 20))
        self.telf_ofi_1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.telf_ofi_1.setObjectName("telf_ofi_1")
        self.foto_info_personal = QtWidgets.QGraphicsView(self.tab_17)
        self.foto_info_personal.setGeometry(QtCore.QRect(630, 10, 261, 151))
        self.foto_info_personal.setObjectName("foto_info_personal")
        self.fech_nac_1 = QtWidgets.QLineEdit(self.tab_17)
        self.fech_nac_1.setGeometry(QtCore.QRect(200, 210, 201, 20))
        self.fech_nac_1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.fech_nac_1.setObjectName("fech_nac_1")
        self.nivel_2.addTab(self.tab_17, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.nivel_2.addTab(self.tab_9, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.nivel_2.addTab(self.tab_10, "")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.nivel_2.addTab(self.tab_11, "")
        self.tab_12 = QtWidgets.QWidget()
        self.tab_12.setObjectName("tab_12")
        self.nivel_2.addTab(self.tab_12, "")
        self.tab_13 = QtWidgets.QWidget()
        self.tab_13.setObjectName("tab_13")
        self.nivel_2.addTab(self.tab_13, "")
        self.tab_14 = QtWidgets.QWidget()
        self.tab_14.setObjectName("tab_14")
        self.nivel_2.addTab(self.tab_14, "")
        self.tab_15 = QtWidgets.QWidget()
        self.tab_15.setObjectName("tab_15")
        self.nivel_2.addTab(self.tab_15, "")
        self.tab_16 = QtWidgets.QWidget()
        self.tab_16.setObjectName("tab_16")
        self.nivel_2.addTab(self.tab_16, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.nivel_2.addTab(self.tab_8, "")
        self.nivel_1.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.nivel_1.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.nivel_1.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.nivel_1.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.nivel_1.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.nivel_1.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.nivel_1.addTab(self.tab_7, "")
        self.Guardar = QtWidgets.QPushButton(self.centralwidget)
        self.Guardar.setEnabled(True)
        self.Guardar.setGeometry(QtCore.QRect(120, 10, 101, 31))
        self.Guardar.setMouseTracking(False)
        self.Guardar.setTabletTracking(False)
        self.Guardar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.Guardar.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.Guardar.setInputMethodHints(QtCore.Qt.ImhNone)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Download/0eb1486e07728e599ecca6d62a475aa4.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Guardar.setIcon(icon)
        self.Guardar.setIconSize(QtCore.QSize(16, 11))
        self.Guardar.setAutoDefault(False)
        self.Guardar.setObjectName("Guardar")
        self.ini_consulta = QtWidgets.QPushButton(self.centralwidget)
        self.ini_consulta.setGeometry(QtCore.QRect(230, 10, 121, 31))
        self.ini_consulta.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ini_consulta.setIconSize(QtCore.QSize(16, 13))
        self.ini_consulta.setObjectName("ini_consulta")
        self.historia_clinica = QtWidgets.QPushButton(self.centralwidget)
        self.historia_clinica.setGeometry(QtCore.QRect(610, 10, 151, 31))
        self.historia_clinica.setObjectName("historia_clinica")
        self.eliminar = QtWidgets.QPushButton(self.centralwidget)
        self.eliminar.setGeometry(QtCore.QRect(470, 10, 121, 31))
        self.eliminar.setObjectName("eliminar")
        self.cerrar = QtWidgets.QPushButton(self.centralwidget)
        self.cerrar.setGeometry(QtCore.QRect(770, 10, 141, 31))
        self.cerrar.setObjectName("cerrar")
        self.boton_nuevo = QtWidgets.QPushButton(self.centralwidget)
        self.boton_nuevo.setGeometry(QtCore.QRect(10, 10, 101, 31))
        self.boton_nuevo.setObjectName("boton_nuevo")
        self.actualizar_datos = QtWidgets.QPushButton(self.centralwidget)
        self.actualizar_datos.setGeometry(QtCore.QRect(360, 10, 101, 31))
        self.actualizar_datos.setObjectName("actualizar_datos")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 917, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.nivel_1.setCurrentIndex(0)
        self.nivel_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.num_expediente_0.setText(_translate("MainWindow", "Expediente Nro."))
        self.titulo_0.setText(_translate("MainWindow", "Titulo"))
        self.nombres.setText(_translate("MainWindow", "Nombre(s)"))
        self.apellidos.setText(_translate("MainWindow", "Apellido(s)"))
        self.domicilio_0.setText(_translate("MainWindow", "Domicilio"))
        self.ciudad_0.setText(_translate("MainWindow", "Ciudad"))
        self.estado_0.setText(_translate("MainWindow", "Estado"))
        self.cod_postal_0.setText(_translate("MainWindow", "Codigo Postal"))
        self.medico_0.setText(_translate("MainWindow", "Medico"))
        self.sexo_0.setText(_translate("MainWindow", "Sexo"))
        self.fech_nac_0.setText(_translate("MainWindow", "Fecha de Nacimiento"))
        self.lug_nac_0.setText(_translate("MainWindow", "Lugar de Nacimiento"))
        self.correo_0.setText(_translate("MainWindow", "Correo Electronico"))
        self.observaciones_0.setText(_translate("MainWindow", "Observaciones"))
        self.ciudad_1_box.setItemText(1, _translate("MainWindow", "Puno"))
        self.ciudad_1_box.setItemText(2, _translate("MainWindow", "Juli"))
        self.ciudad_1_box.setItemText(3, _translate("MainWindow", "Azángaro"))
        self.ciudad_1_box.setItemText(4, _translate("MainWindow", "Lampa"))
        self.ciudad_1_box.setItemText(5, _translate("MainWindow", "Ayaviry"))
        self.ciudad_1_box.setItemText(6, _translate("MainWindow", "Juliaca"))
        self.ciudad_1_box.setItemText(7, _translate("MainWindow", "Macusani"))
        self.ciudad_1_box.setItemText(8, _translate("MainWindow", "Huancané"))
        self.ciudad_1_box.setItemText(9, _translate("MainWindow", "Yunguyo"))
        self.ciudad_1_box.setItemText(10, _translate("MainWindow", "Moho"))
        self.ciudad_1_box.setItemText(11, _translate("MainWindow", "Ilave"))
        self.ciudad_1_box.setItemText(12, _translate("MainWindow", "Sandia"))
        self.estado_1_box.setItemText(1, _translate("MainWindow", "Perú"))
        self.estado_1_box.setItemText(2, _translate("MainWindow", "Bolivia"))
        self.sexo_1_box.setItemText(1, _translate("MainWindow", "Masculino"))
        self.sexo_1_box.setItemText(2, _translate("MainWindow", "Femenino"))
        self.medico_1_box.setItemText(1, _translate("MainWindow", "Jhoel Churata Torres"))
        self.medico_1_box.setItemText(2, _translate("MainWindow", "Miguel Alex"))
        self.num_seguro_0.setText(_translate("MainWindow", "No.de Seguridad Social"))
        self.edad_0.setText(_translate("MainWindow", "Edad"))
        self.telf_dom_0.setText(_translate("MainWindow", "Telefono Dom."))
        self.telf_ofi_0.setText(_translate("MainWindow", "Teléfono Oficina"))
        self.nivel_2.setTabText(self.nivel_2.indexOf(self.tab_17), _translate("MainWindow", "Informacion Personal"))
        self.nivel_2.setTabText(self.nivel_2.indexOf(self.tab_9), _translate("MainWindow", "Antecedentes"))
        self.nivel_2.setTabText(self.nivel_2.indexOf(self.tab_10), _translate("MainWindow", "Exploración Fisica"))
        self.nivel_2.setTabText(self.nivel_2.indexOf(self.tab_11), _translate("MainWindow", "Interrogatorio"))
        self.nivel_2.setTabText(self.nivel_2.indexOf(self.tab_12), _translate("MainWindow", "Estilo de Vida"))
        self.nivel_2.setTabText(self.nivel_2.indexOf(self.tab_13), _translate("MainWindow", "Documentos"))
        self.nivel_2.setTabText(self.nivel_2.indexOf(self.tab_14), _translate("MainWindow", "Alergias"))
        self.nivel_2.setTabText(self.nivel_2.indexOf(self.tab_15), _translate("MainWindow", "Incapacidad"))
        self.nivel_2.setTabText(self.nivel_2.indexOf(self.tab_16), _translate("MainWindow", "Estado de Cuenta"))
        self.nivel_2.setTabText(self.nivel_2.indexOf(self.tab_8), _translate("MainWindow", "Consultas"))
        self.nivel_1.setTabText(self.nivel_1.indexOf(self.tab), _translate("MainWindow", "Expedientes"))
        self.nivel_1.setTabText(self.nivel_1.indexOf(self.tab_2), _translate("MainWindow", "Agenda"))
        self.nivel_1.setTabText(self.nivel_1.indexOf(self.tab_3), _translate("MainWindow", "Consultorios"))
        self.nivel_1.setTabText(self.nivel_1.indexOf(self.tab_4), _translate("MainWindow", "Dashboard"))
        self.nivel_1.setTabText(self.nivel_1.indexOf(self.tab_5), _translate("MainWindow", "Medicos"))
        self.nivel_1.setTabText(self.nivel_1.indexOf(self.tab_6), _translate("MainWindow", "Asistentes"))
        self.nivel_1.setTabText(self.nivel_1.indexOf(self.tab_7), _translate("MainWindow", "Reportes"))
        self.Guardar.setText(_translate("MainWindow", "Guardar Datos"))
        self.ini_consulta.setText(_translate("MainWindow", "Iniciar Consulta"))
        self.historia_clinica.setText(_translate("MainWindow", "Historia Clinica"))
        self.eliminar.setText(_translate("MainWindow", "Eliminar"))
        self.cerrar.setText(_translate("MainWindow", "Cerrar"))
        self.boton_nuevo.setText(_translate("MainWindow", "Nuevo"))
        self.actualizar_datos.setText(_translate("MainWindow", "Actualizar Datos"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

